import { Permission } from '../../../common/enums/permission.enum'
import { UserRole } from '../../../common/interfaces/authenticated-request.interface'

/**
 * Default permission matrix for each role.
 * GLOBAL_ADMIN is omitted — they always have all permissions.
 *
 * This matrix matches the static role-based permissions that existed
 * before the dynamic permission system was introduced.
 */
export const DEFAULT_PERMISSIONS: Record<string, Permission[]> = {
  [UserRole.TENANT_ADMIN]: [
    // Dashboard
    Permission.DASHBOARD_VIEW,
    // Alerts
    Permission.ALERTS_VIEW,
    Permission.ALERTS_INVESTIGATE,
    Permission.ALERTS_ACKNOWLEDGE,
    Permission.ALERTS_CLOSE,
    Permission.ALERTS_ESCALATE,
    // Cases
    Permission.CASES_VIEW,
    Permission.CASES_CREATE,
    Permission.CASES_UPDATE,
    Permission.CASES_DELETE,
    Permission.CASES_ASSIGN,
    Permission.CASES_CHANGE_STATUS,
    Permission.CASES_ADD_COMMENT,
    Permission.CASES_DELETE_COMMENT,
    Permission.CASES_ADD_TASK,
    Permission.CASES_UPDATE_TASK,
    Permission.CASES_DELETE_TASK,
    Permission.CASES_ADD_ARTIFACT,
    Permission.CASES_DELETE_ARTIFACT,
    // Incidents
    Permission.INCIDENTS_VIEW,
    Permission.INCIDENTS_CREATE,
    Permission.INCIDENTS_UPDATE,
    Permission.INCIDENTS_DELETE,
    Permission.INCIDENTS_ADD_TIMELINE,
    Permission.INCIDENTS_CHANGE_STATUS,
    // Connectors
    Permission.CONNECTORS_VIEW,
    Permission.CONNECTORS_CREATE,
    Permission.CONNECTORS_UPDATE,
    Permission.CONNECTORS_DELETE,
    Permission.CONNECTORS_TEST,
    Permission.CONNECTORS_SYNC,
    // Correlation
    Permission.CORRELATION_VIEW,
    Permission.CORRELATION_CREATE,
    Permission.CORRELATION_UPDATE,
    Permission.CORRELATION_DELETE,
    Permission.CORRELATION_TOGGLE,
    // Detection Rules
    Permission.DETECTION_RULES_VIEW,
    Permission.DETECTION_RULES_CREATE,
    Permission.DETECTION_RULES_UPDATE,
    Permission.DETECTION_RULES_DELETE,
    Permission.DETECTION_RULES_TOGGLE,
    // Hunt
    Permission.HUNT_VIEW,
    Permission.HUNT_CREATE,
    Permission.HUNT_UPDATE,
    Permission.HUNT_DELETE,
    Permission.HUNT_EXECUTE,
    // Reports
    Permission.REPORTS_VIEW,
    Permission.REPORTS_CREATE,
    Permission.REPORTS_DELETE,
    Permission.REPORTS_EXPORT,
    // Admin - Users
    Permission.ADMIN_USERS_VIEW,
    Permission.ADMIN_USERS_CREATE,
    Permission.ADMIN_USERS_UPDATE,
    Permission.ADMIN_USERS_DELETE,
    Permission.ADMIN_USERS_BLOCK,
    Permission.ADMIN_USERS_RESTORE,
    // Admin - Tenants (view only for TENANT_ADMIN)
    Permission.ADMIN_TENANTS_VIEW,
    // Intel
    Permission.INTEL_VIEW,
    // SOAR
    Permission.SOAR_VIEW,
    Permission.SOAR_CREATE,
    Permission.SOAR_UPDATE,
    Permission.SOAR_DELETE,
    Permission.SOAR_EXECUTE,
    // AI Agents
    Permission.AI_AGENTS_VIEW,
    Permission.AI_AGENTS_CREATE,
    Permission.AI_AGENTS_UPDATE,
    Permission.AI_AGENTS_DELETE,
    // Cloud Security
    Permission.CLOUD_SECURITY_VIEW,
    Permission.CLOUD_SECURITY_CREATE,
    Permission.CLOUD_SECURITY_UPDATE,
    Permission.CLOUD_SECURITY_DELETE,
    // Compliance
    Permission.COMPLIANCE_VIEW,
    Permission.COMPLIANCE_CREATE,
    Permission.COMPLIANCE_UPDATE,
    // Attack Paths
    Permission.ATTACK_PATHS_VIEW,
    Permission.ATTACK_PATHS_CREATE,
    Permission.ATTACK_PATHS_UPDATE,
    Permission.ATTACK_PATHS_DELETE,
    // UEBA
    Permission.UEBA_VIEW,
    Permission.UEBA_CREATE,
    Permission.UEBA_UPDATE,
    // Normalization
    Permission.NORMALIZATION_VIEW,
    Permission.NORMALIZATION_CREATE,
    Permission.NORMALIZATION_UPDATE,
    Permission.NORMALIZATION_DELETE,
    // Vulnerabilities
    Permission.VULNERABILITIES_VIEW,
    Permission.VULNERABILITIES_CREATE,
    Permission.VULNERABILITIES_UPDATE,
    Permission.VULNERABILITIES_DELETE,
    // Explorer
    Permission.EXPLORER_VIEW,
    Permission.EXPLORER_QUERY,
    // Notifications
    Permission.NOTIFICATIONS_VIEW,
    Permission.NOTIFICATIONS_MANAGE,
    // Profile
    Permission.PROFILE_VIEW,
    Permission.PROFILE_UPDATE,
    // Settings
    Permission.SETTINGS_VIEW,
    Permission.SETTINGS_UPDATE,
    // Note: ROLE_SETTINGS intentionally excluded — only GLOBAL_ADMIN can manage roles by default.
  ],

  [UserRole.SOC_ANALYST_L2]: [
    Permission.DASHBOARD_VIEW,
    Permission.ALERTS_VIEW,
    Permission.ALERTS_INVESTIGATE,
    Permission.ALERTS_ACKNOWLEDGE,
    Permission.ALERTS_CLOSE,
    Permission.ALERTS_ESCALATE,
    Permission.CASES_VIEW,
    Permission.CASES_CREATE,
    Permission.CASES_UPDATE,
    Permission.CASES_ASSIGN,
    Permission.CASES_CHANGE_STATUS,
    Permission.CASES_ADD_COMMENT,
    Permission.CASES_ADD_TASK,
    Permission.CASES_UPDATE_TASK,
    Permission.CASES_ADD_ARTIFACT,
    Permission.INCIDENTS_VIEW,
    Permission.INCIDENTS_CREATE,
    Permission.INCIDENTS_UPDATE,
    Permission.INCIDENTS_ADD_TIMELINE,
    Permission.INCIDENTS_CHANGE_STATUS,
    Permission.CONNECTORS_VIEW,
    Permission.CONNECTORS_CREATE,
    Permission.CONNECTORS_UPDATE,
    Permission.CONNECTORS_DELETE,
    Permission.CONNECTORS_TEST,
    Permission.CONNECTORS_SYNC,
    Permission.CORRELATION_VIEW,
    Permission.CORRELATION_CREATE,
    Permission.CORRELATION_UPDATE,
    Permission.CORRELATION_DELETE,
    Permission.CORRELATION_TOGGLE,
    Permission.DETECTION_RULES_VIEW,
    Permission.DETECTION_RULES_CREATE,
    Permission.DETECTION_RULES_UPDATE,
    Permission.DETECTION_RULES_DELETE,
    Permission.DETECTION_RULES_TOGGLE,
    Permission.HUNT_VIEW,
    Permission.HUNT_CREATE,
    Permission.HUNT_UPDATE,
    Permission.HUNT_DELETE,
    Permission.HUNT_EXECUTE,
    Permission.REPORTS_VIEW,
    Permission.REPORTS_EXPORT,
    Permission.INTEL_VIEW,
    Permission.SOAR_VIEW,
    Permission.SOAR_CREATE,
    Permission.SOAR_UPDATE,
    Permission.SOAR_DELETE,
    Permission.SOAR_EXECUTE,
    Permission.AI_AGENTS_VIEW,
    Permission.CLOUD_SECURITY_VIEW,
    Permission.CLOUD_SECURITY_CREATE,
    Permission.CLOUD_SECURITY_UPDATE,
    Permission.CLOUD_SECURITY_DELETE,
    Permission.COMPLIANCE_VIEW,
    Permission.ATTACK_PATHS_VIEW,
    Permission.ATTACK_PATHS_CREATE,
    Permission.ATTACK_PATHS_UPDATE,
    Permission.ATTACK_PATHS_DELETE,
    Permission.UEBA_VIEW,
    Permission.UEBA_CREATE,
    Permission.UEBA_UPDATE,
    Permission.VULNERABILITIES_VIEW,
    Permission.VULNERABILITIES_CREATE,
    Permission.VULNERABILITIES_UPDATE,
    Permission.VULNERABILITIES_DELETE,
    Permission.EXPLORER_VIEW,
    Permission.EXPLORER_QUERY,
    Permission.NOTIFICATIONS_VIEW,
    Permission.NOTIFICATIONS_MANAGE,
    Permission.PROFILE_VIEW,
    Permission.PROFILE_UPDATE,
    Permission.SETTINGS_VIEW,
    Permission.SETTINGS_UPDATE,
  ],

  [UserRole.THREAT_HUNTER]: [
    Permission.DASHBOARD_VIEW,
    Permission.ALERTS_VIEW,
    Permission.ALERTS_INVESTIGATE,
    Permission.ALERTS_ACKNOWLEDGE,
    Permission.ALERTS_CLOSE,
    Permission.ALERTS_ESCALATE,
    Permission.CASES_VIEW,
    Permission.CASES_CREATE,
    Permission.CASES_UPDATE,
    Permission.CASES_CHANGE_STATUS,
    Permission.CASES_ADD_COMMENT,
    Permission.CASES_ADD_TASK,
    Permission.CASES_UPDATE_TASK,
    Permission.CASES_ADD_ARTIFACT,
    Permission.INCIDENTS_VIEW,
    Permission.INCIDENTS_CREATE,
    Permission.INCIDENTS_UPDATE,
    Permission.INCIDENTS_ADD_TIMELINE,
    Permission.INCIDENTS_CHANGE_STATUS,
    Permission.CORRELATION_VIEW,
    Permission.CORRELATION_CREATE,
    Permission.CORRELATION_UPDATE,
    Permission.CORRELATION_DELETE,
    Permission.CORRELATION_TOGGLE,
    Permission.DETECTION_RULES_VIEW,
    Permission.DETECTION_RULES_CREATE,
    Permission.DETECTION_RULES_UPDATE,
    Permission.DETECTION_RULES_DELETE,
    Permission.DETECTION_RULES_TOGGLE,
    Permission.HUNT_VIEW,
    Permission.HUNT_CREATE,
    Permission.HUNT_UPDATE,
    Permission.HUNT_DELETE,
    Permission.HUNT_EXECUTE,
    Permission.INTEL_VIEW,
    Permission.ATTACK_PATHS_VIEW,
    Permission.ATTACK_PATHS_CREATE,
    Permission.ATTACK_PATHS_UPDATE,
    Permission.VULNERABILITIES_VIEW,
    Permission.VULNERABILITIES_CREATE,
    Permission.VULNERABILITIES_UPDATE,
    Permission.EXPLORER_VIEW,
    Permission.EXPLORER_QUERY,
    Permission.REPORTS_VIEW,
    Permission.REPORTS_CREATE,
    Permission.REPORTS_EXPORT,
    Permission.COMPLIANCE_VIEW,
    Permission.NOTIFICATIONS_VIEW,
    Permission.NOTIFICATIONS_MANAGE,
    Permission.PROFILE_VIEW,
    Permission.PROFILE_UPDATE,
    Permission.SETTINGS_VIEW,
    Permission.SETTINGS_UPDATE,
  ],

  [UserRole.SOC_ANALYST_L1]: [
    Permission.DASHBOARD_VIEW,
    Permission.ALERTS_VIEW,
    Permission.ALERTS_INVESTIGATE,
    Permission.ALERTS_ACKNOWLEDGE,
    Permission.ALERTS_CLOSE,
    Permission.ALERTS_ESCALATE,
    Permission.CASES_VIEW,
    Permission.CASES_CREATE,
    Permission.CASES_UPDATE,
    Permission.CASES_CHANGE_STATUS,
    Permission.CASES_ADD_COMMENT,
    // Note: CASES_ADD_TASK, CASES_UPDATE_TASK, CASES_ADD_ARTIFACT intentionally
    // excluded — L1 analysts get these only through case-ownership bypass on the frontend.
    Permission.INCIDENTS_VIEW,
    Permission.INCIDENTS_CREATE,
    Permission.INCIDENTS_ADD_TIMELINE,
    Permission.CORRELATION_VIEW,
    Permission.CORRELATION_CREATE,
    Permission.CORRELATION_UPDATE,
    Permission.INTEL_VIEW,
    Permission.VULNERABILITIES_VIEW,
    Permission.VULNERABILITIES_CREATE,
    Permission.VULNERABILITIES_UPDATE,
    Permission.EXPLORER_VIEW,
    Permission.EXPLORER_QUERY,
    Permission.REPORTS_VIEW,
    Permission.REPORTS_EXPORT,
    Permission.COMPLIANCE_VIEW,
    Permission.NOTIFICATIONS_VIEW,
    Permission.NOTIFICATIONS_MANAGE,
    Permission.PROFILE_VIEW,
    Permission.PROFILE_UPDATE,
    Permission.SETTINGS_VIEW,
    Permission.SETTINGS_UPDATE,
  ],

  [UserRole.EXECUTIVE_READONLY]: [
    Permission.DASHBOARD_VIEW,
    Permission.ALERTS_VIEW,
    Permission.CASES_VIEW,
    Permission.INCIDENTS_VIEW,
    Permission.REPORTS_VIEW,
    Permission.REPORTS_EXPORT,
    Permission.COMPLIANCE_VIEW,
    Permission.INTEL_VIEW,
    Permission.NOTIFICATIONS_VIEW,
    Permission.PROFILE_VIEW,
    Permission.PROFILE_UPDATE,
    Permission.SETTINGS_VIEW,
    Permission.SETTINGS_UPDATE,
  ],
}

/**
 * Configurable roles — GLOBAL_ADMIN is excluded because it always
 * has full access and its permissions cannot be modified.
 */
export const CONFIGURABLE_ROLES: string[] = [
  UserRole.TENANT_ADMIN,
  UserRole.SOC_ANALYST_L2,
  UserRole.THREAT_HUNTER,
  UserRole.SOC_ANALYST_L1,
  UserRole.EXECUTIVE_READONLY,
]
